name: Test SSH Connection

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          known_hosts: ${{ secrets.LIGHTSAIL_KNOWN_HOSTS }}

      - name: Create timestamp file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            echo "Last GitHub Actions run: $(date)" > ~/github-actions-test.txt
            cat ~/github-actions-test.txt
